include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = OrbitWindowPrefs
OrbitWindowPrefs_FILES = OWRootListController.m
OrbitWindowPrefs_FRAMEWORKS = UIKit
OrbitWindowPrefs_PRIVATE_FRAMEWORKS = Preferences
OrbitWindowPrefs_INSTALL_PATH = /Library/PreferenceBundles
OrbitWindowPrefs_CFLAGS = -fobjc-arc -Wno-deprecated-declarations -Wno-arc-performSelector-leaks

include $(THEOS_MAKE_PATH)/bundle.mk
